{% macro clean_illness_value(illness_column) %}
CASE {{illness_column}}
WHEN 'RADIOGRAFIA' THEN 'Radiografía'
WHEN '1ER_VEZ_EN_CLINICA_N_V' THEN 'Primera Vez En Clínica N V'
WHEN 'LIMPIEZA' THEN 'Limpieza'
WHEN 'PASTA_DENTAL' THEN 'Pasta Dental'
WHEN 'SOLAMENTE_REVISION' THEN 'Solamente Revisión'
WHEN 'RESTAURACIONES' THEN 'Restauraciones'
WHEN 'EXTRACCION_DIENTES_PERMANENTES' THEN 'Extracción Dientes Permanentes'
WHEN '1ERA_VEZ_EN_EL_A__O' THEN 'Primera Vez En El Año'
WHEN 'RESINA' THEN 'Resina'
WHEN 'EXTRACCION_DIENTES_DE_LECHE' THEN 'Extracción Dientes De Leche'
WHEN 'SELLADORES' THEN 'Selladores'
WHEN 'SD_FLUOR' THEN 'Sd Fluor'
WHEN 'TECNICA_EN_CEPILLADO' THEN 'Técnica En Cepillado'
WHEN 'FLUOR' THEN 'Flúor'
WHEN 'AMALGAMA' THEN 'Amalgama'
WHEN 'ZE__TEMPORAL_' THEN 'Ze Temporal'
WHEN '2DA_VEZ_EN_EL_A__O' THEN 'Segunda Vez En El Año'
WHEN 'CONDUCTA_NEGATIVA' THEN 'Conducta Negativa'
WHEN 'PROBLEMAS_DESARROLLO_DE_LENGUAJE' THEN 'Problemas Desarrollo De Lenguaje'
WHEN 'PROBLEMAS_DE_COMPORTAMIENTO' THEN 'Problemas De Comportamiento'
WHEN 'FAMILIAS_DISFUNCIONALES' THEN 'Familias Disfuncionales'
WHEN 'PROBLEMAS_EN_LA_ESCUELA' THEN 'Problemas En La Escuela'
WHEN 'DUELO' THEN 'Duelo'
WHEN 'DEFICIENCIA_DE_APRENDIZAJE' THEN 'Deficiencia De Aprendizaje'
WHEN 'DISCAPACIDAD_DE_ATENCION_INCLUSIVA' THEN 'Discapacidad De Atención Inclusiva'
WHEN 'ANSIEDAD' THEN 'Ansiedad'
WHEN 'TRAUMA' THEN 'Trauma'
WHEN 'TRASTORNO_DE_LA_PERSONALIDAD' THEN 'Trastorno De La Personalidad'
WHEN 'ESTR__S_ESTACIONAL_AGUDO' THEN 'Estrés Estacional Agudo'
WHEN 'DIFICULTAD_X_OTRAS_PATOLOGIAS' THEN 'Dificultad X Otras Patologías'
WHEN 'FAMILIA_MATRIMONIOS' THEN 'Familia Matrimonios'
WHEN 'MALTRATO__EMOCIONAL_VERBAL_FISICO_PSICOLOGICO' THEN 'Maltrato Emocional Verbal Físico Psicológico'
WHEN 'C_FECAL' THEN 'C Fecal'
WHEN 'HEMATOLOGIA' THEN 'Hematología'
WHEN 'EGH' THEN 'EGH'
WHEN 'PLAQUETAS' THEN 'Plaquetas'
WHEN 'EGO' THEN 'Ego'
WHEN 'BHC_COMPLETA' THEN 'Bhc Completa'
WHEN 'HEMATOCRITO' THEN 'Hematocrito'
WHEN 'H_PYLORI' THEN 'H. Pylori'
WHEN 'ASLO' THEN 'ASLO'
WHEN 'Alergias' THEN 'Alergias'
WHEN 'Nutrici__n__Anemia__Obesidad' THEN 'Nutrición, Anemia, Obesidad'
WHEN 'Infecci__n_Respiratorio__Viral__Gripe' THEN 'Infección Respiratoria Viral, Gripe'
WHEN 'Piel_Condici__n_no_Infectada' THEN 'Piel Condición No Infectada'
WHEN 'Parasitosis' THEN 'Parasitosis'
WHEN 'EDA__Diarrea___Estre__imiento' THEN 'EDA, Diarrea, Estreñimiento'
WHEN 'ERGE__Gastritis__H_Pylori' THEN 'ERGE, Gastritis, H. Pylori'
WHEN 'Citado' THEN 'Citado'
WHEN 'Amigdalitis__Dolor_de_garganta' THEN 'Amigdalitis, Dolor De Garganta'
WHEN 'Piel_Condici__n_infectada__Herida' THEN 'Piel Condición Infectada, Herida'
WHEN 'Bucal' THEN 'Bucal'
WHEN 'Otitis_externa__media' THEN 'Otitis Externa, Media'
WHEN 'Infecci__n_Urinaria' THEN 'Infección Urinaria'
WHEN 'Nauseas__V__mito' THEN 'Náuseas, Vómito'
WHEN 'Asma__EPOC' THEN 'Asma, EPOC'
WHEN 'Ojos' THEN 'Ojos'
WHEN 'Infecci__n_Respiratorio__Bacteriana' THEN 'Infección Respiratoria Bacteriana'
WHEN 'Neurolog__a__Epilepsia__Parkinson' THEN 'Neurología, Epilepsia, Parkinson'
WHEN 'Dolor_Cuerpo__Cabeza__Migra__a' THEN 'Dolor Cuerpo, Cabeza, Migraña'
WHEN 'Colesterol' THEN 'Colesterol'
WHEN 'Tendones__Tejido_Blando' THEN 'Tendones, Tejido Blando'
WHEN 'Fiebre__Dengue' THEN 'Fiebre, Dengue'
WHEN 'Intestin__Colitis' THEN 'Intestino, Colitis'
WHEN 'Fiebre' THEN 'Fiebre'
WHEN 'Tx_Odontolog__a' THEN 'Tx Odontología'
WHEN 'Tx_Higiene_Bucal' THEN 'Tx Higiene Bucal'
WHEN 'H__gado__Hepatopat__a__Hernia' THEN 'Hígado, Hepatopatía, Hernia'
WHEN 'Ginecolog__a' THEN 'Ginecología'
WHEN 'Di__betes' THEN 'Diabetes'
WHEN 'Transferencia_a_Hospital' THEN 'Transferencia A Hospital'
WHEN 'Tx_Psicolog__a' THEN 'Tx Psicología'
WHEN 'Mamas' THEN 'Mamas'
WHEN 'DEPRESION' THEN 'Depresión'
WHEN 'VIOLENCIA_DOMESTICA' THEN 'Violencia Doméstica'
WHEN 'PSICOSIS' THEN 'Psicosis'
WHEN 'SUICIDIO' THEN 'Suicidio'
WHEN 'HCG_SUERO' THEN 'HCG Suero'
WHEN 'VIH' THEN 'VIH'
WHEN 'VDRL_RPR' THEN 'VDRL RPR'
WHEN 'GLICEMIA' THEN 'Glicemia'
WHEN 'TRIGLICERIDOS' THEN 'Triglicéridos'
WHEN 'HDL' THEN 'HDL'
WHEN 'A_URICO' THEN 'Ácido Úrico'
WHEN 'F_REUMATOIDEO' THEN 'Factor Reumatoideo'
WHEN 'CREATININA' THEN 'Creatinina'
WHEN 'PCR' THEN 'PCR'
WHEN 'MALARIA' THEN 'Malaria'
WHEN 'Muscular__Tendones' THEN 'Muscular, Tendones'
WHEN 'Problemas_emocionales' THEN 'Problemas Emocionales'
WHEN 'Hipertensi__n__Condici__n_Card__aca' THEN 'Hipertensión, Condición Cardíaca'
WHEN 'Espalda__Columna_vertebral' THEN 'Espalda, Columna Vertebral'
WHEN 'V__rtigo__Mareo' THEN 'Vértigo, Mareo'
WHEN 'Artritis__OA' THEN 'Artritis, OA'
WHEN 'Embarazo__Prenatal' THEN 'Embarazo, Prenatal'
WHEN 'Renal__RC' THEN 'Renal, RC'
WHEN 'Menopausia__Climaterio' THEN 'Menopausia, Climaterio'
WHEN 'C__rvico_Vaginitis__Hongo_Vaginal' THEN 'Cérvico Vaginitis, Hongo Vaginal'
WHEN 'Varises__Insuficiencia_venosa' THEN 'Várices, Insuficiencia Venosa'
WHEN 'Gl__ndula__Tiroides__Pr__stata' THEN 'Glándula, Tiroides, Próstata'
WHEN 'TB' THEN 'TB'
WHEN 'Visita_a_la_Comunidad' THEN 'Visita A La Comunidad'
END
{%endmacro%}