{% macro clean_illness_value(illness_column) %}
    case
        {{ illness_column }}
        when 'RADIOGRAFIA'
        then 'Radiografía'
        when '1ER_VEZ_EN_CLINICA_N_V'
        then 'Primera Vez En Clínica N V'
        when 'LIMPIEZA'
        then 'Limpieza'
        when 'PASTA_DENTAL'
        then 'Pasta Dental'
        when 'SOLAMENTE_REVISION'
        then 'Solamente Revisión'
        when 'RESTAURACIONES'
        then 'Restauraciones'
        when 'EXTRACCION_DIENTES_PERMANENTES'
        then 'Extracción Dientes Permanentes'
        when '1ERA_VEZ_EN_EL_A__O'
        then 'Primera Vez En El Año'
        when 'RESINA'
        then 'Resina'
        when 'EXTRACCION_DIENTES_DE_LECHE'
        then 'Extracción Dientes De Leche'
        when 'SELLADORES'
        then 'Selladores'
        when 'SD_FLUOR'
        then 'Sd Fluor'
        when 'TECNICA_EN_CEPILLADO'
        then 'Técnica En Cepillado'
        when 'FLUOR'
        then 'Flúor'
        when 'AMALGAMA'
        then 'Amalgama'
        when 'ZE__TEMPORAL_'
        then 'Ze Temporal'
        when '2DA_VEZ_EN_EL_A__O'
        then 'Segunda Vez En El Año'
        when 'CONDUCTA_NEGATIVA'
        then 'Conducta Negativa'
        when 'PROBLEMAS_DESARROLLO_DE_LENGUAJE'
        then 'Problemas Desarrollo De Lenguaje'
        when 'PROBLEMAS_DE_COMPORTAMIENTO'
        then 'Problemas De Comportamiento'
        when 'FAMILIAS_DISFUNCIONALES'
        then 'Familias Disfuncionales'
        when 'PROBLEMAS_EN_LA_ESCUELA'
        then 'Problemas En La Escuela'
        when 'DUELO'
        then 'Duelo'
        when 'DEFICIENCIA_DE_APRENDIZAJE'
        then 'Deficiencia De Aprendizaje'
        when 'DISCAPACIDAD_DE_ATENCION_INCLUSIVA'
        then 'Discapacidad De Atención Inclusiva'
        when 'ANSIEDAD'
        then 'Ansiedad'
        when 'TRAUMA'
        then 'Trauma'
        when 'TRASTORNO_DE_LA_PERSONALIDAD'
        then 'Trastorno De La Personalidad'
        when 'ESTR__S_ESTACIONAL_AGUDO'
        then 'Estrés Estacional Agudo'
        when 'DIFICULTAD_X_OTRAS_PATOLOGIAS'
        then 'Dificultad X Otras Patologías'
        when 'FAMILIA_MATRIMONIOS'
        then 'Familia Matrimonios'
        when 'MALTRATO__EMOCIONAL_VERBAL_FISICO_PSICOLOGICO'
        then 'Maltrato Emocional Verbal Físico Psicológico'
        when 'C_FECAL'
        then 'C Fecal'
        when 'HEMATOLOGIA'
        then 'Hematología'
        when 'EGH'
        then 'EGH'
        when 'PLAQUETAS'
        then 'Plaquetas'
        when 'EGO'
        then 'Ego'
        when 'BHC_COMPLETA'
        then 'Bhc Completa'
        when 'HEMATOCRITO'
        then 'Hematocrito'
        when 'H_PYLORI'
        then 'H. Pylori'
        when 'ASLO'
        then 'ASLO'
        when 'Alergias'
        then 'Alergias'
        when 'Nutrici__n__Anemia__Obesidad'
        then 'Nutrición, Anemia, Obesidad'
        when 'Infecci__n_Respiratorio__Viral__Gripe'
        then 'Infección Respiratoria Viral, Gripe'
        when 'Piel_Condici__n_no_Infectada'
        then 'Piel Condición No Infectada'
        when 'Parasitosis'
        then 'Parasitosis'
        when 'EDA__Diarrea___Estre__imiento'
        then 'EDA, Diarrea, Estreñimiento'
        when 'ERGE__Gastritis__H_Pylori'
        then 'ERGE, Gastritis, H. Pylori'
        when 'Citado'
        then 'Citado'
        when 'Amigdalitis__Dolor_de_garganta'
        then 'Amigdalitis, Dolor De Garganta'
        when 'Piel_Condici__n_infectada__Herida'
        then 'Piel Condición Infectada, Herida'
        when 'Bucal'
        then 'Bucal'
        when 'Otitis_externa__media'
        then 'Otitis Externa, Media'
        when 'Infecci__n_Urinaria'
        then 'Infección Urinaria'
        when 'Nauseas__V__mito'
        then 'Náuseas, Vómito'
        when 'Asma__EPOC'
        then 'Asma, EPOC'
        when 'Ojos'
        then 'Ojos'
        when 'Infecci__n_Respiratorio__Bacteriana'
        then 'Infección Respiratoria Bacteriana'
        when 'Neurolog__a__Epilepsia__Parkinson'
        then 'Neurología, Epilepsia, Parkinson'
        when 'Dolor_Cuerpo__Cabeza__Migra__a'
        then 'Dolor Cuerpo, Cabeza, Migraña'
        when 'Colesterol'
        then 'Colesterol'
        when 'Tendones__Tejido_Blando'
        then 'Tendones, Tejido Blando'
        when 'Fiebre__Dengue'
        then 'Fiebre, Dengue'
        when 'Intestin__Colitis'
        then 'Intestino, Colitis'
        when 'Fiebre'
        then 'Fiebre'
        when 'Tx_Odontolog__a'
        then 'Tx Odontología'
        when 'Tx_Higiene_Bucal'
        then 'Tx Higiene Bucal'
        when 'H__gado__Hepatopat__a__Hernia'
        then 'Hígado, Hepatopatía, Hernia'
        when 'Ginecolog__a'
        then 'Ginecología'
        when 'Di__betes'
        then 'Diabetes'
        when 'Transferencia_a_Hospital'
        then 'Transferencia A Hospital'
        when 'Tx_Psicolog__a'
        then 'Tx Psicología'
        when 'Mamas'
        then 'Mamas'
        when 'DEPRESION'
        then 'Depresión'
        when 'VIOLENCIA_DOMESTICA'
        then 'Violencia Doméstica'
        when 'PSICOSIS'
        then 'Psicosis'
        when 'SUICIDIO'
        then 'Suicidio'
        when 'HCG_SUERO'
        then 'HCG Suero'
        when 'VIH'
        then 'VIH'
        when 'VDRL_RPR'
        then 'VDRL RPR'
        when 'GLICEMIA'
        then 'Glicemia'
        when 'TRIGLICERIDOS'
        then 'Triglicéridos'
        when 'HDL'
        then 'HDL'
        when 'A_URICO'
        then 'Ácido Úrico'
        when 'F_REUMATOIDEO'
        then 'Factor Reumatoideo'
        when 'CREATININA'
        then 'Creatinina'
        when 'PCR'
        then 'PCR'
        when 'MALARIA'
        then 'Malaria'
        when 'Muscular__Tendones'
        then 'Muscular, Tendones'
        when 'Problemas_emocionales'
        then 'Problemas Emocionales'
        when 'Hipertensi__n__Condici__n_Card__aca'
        then 'Hipertensión, Condición Cardíaca'
        when 'Espalda__Columna_vertebral'
        then 'Espalda, Columna Vertebral'
        when 'V__rtigo__Mareo'
        then 'Vértigo, Mareo'
        when 'Artritis__OA'
        then 'Artritis, OA'
        when 'Embarazo__Prenatal'
        then 'Embarazo, Prenatal'
        when 'Renal__RC'
        then 'Renal, RC'
        when 'Menopausia__Climaterio'
        then 'Menopausia, Climaterio'
        when 'C__rvico_Vaginitis__Hongo_Vaginal'
        then 'Cérvico Vaginitis, Hongo Vaginal'
        when 'Varises__Insuficiencia_venosa'
        then 'Várices, Insuficiencia Venosa'
        when 'Gl__ndula__Tiroides__Pr__stata'
        then 'Glándula, Tiroides, Próstata'
        when 'TB'
        then 'TB'
        when 'Visita_a_la_Comunidad'
        then 'Visita A La Comunidad'
    end
{% endmacro %}
